<a href="https://colab.research.google.com/github/AshaPandian/ML/blob/main/PGDCB_Week1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Week 1 --- UNIT 1**

In [ ]:
x=10
print(x)

10


In [ ]:
x=input("Enter the value of x:")
print(x)
print(type(x))

Enter the value of x:10
10
<class 'str'>


In [ ]:
x=int(input("Enter the value of x:"))
print(x)
print(type(x))

Enter the value of x:10
10
<class 'int'>


In [ ]:
6**2     #** is exponentiation

36

In [ ]:
6^2         # ^ does Xor operation here.... 6 XOR 2 

4

In [ ]:
name = input("Enter your name: ")
print("Your name is: ", name)
print(type(name))
 
age =int(input("Enter your age: "))
print("Your name is: ", age)
print(type(age))
 
sal = float(input("Enter your sal: "))
print("Your name is: ", sal)
print(type(sal))
 
age = 22
sal = 10.50
complex = 3+5j
print(type(age))
print(type(sal))
print(type(complex))

Enter your name: Asha
Your name is:  Asha
<class 'str'>
Enter your age: 33
Your name is:  33
<class 'int'>
Enter your sal: 21345.00
Your name is:  21345.0
<class 'float'>
<class 'int'>
<class 'float'>
<class 'complex'>


In [ ]:
#Indendation

for i in range(1,5):
  print(i)
print("Inside for")
print("out of for loop")

1
2
3
4
Inside for
out of for loop


In [ ]:
x=y=z=50
print("x=",x,"y=",y,"z=",z)
a,b,c=1,2,3
print("a=",a,"b=",b,"c=",c)

x= 50 y= 50 z= 50
a= 1 b= 2 c= 3


In [ ]:
import keyword
print(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


In [ ]:
import sys
print("Python version")
print (sys.version)


Python version
3.7.10 (default, Feb 20 2021, 21:17:23) 
[GCC 7.5.0]


In [ ]:
my_dna = "ATGCGTA" 
print(my_dna) 
# change the value of my_dna 
my_Dna = "TGGTCCA"
print(my_Dna)

ATGCGTA
TGGTCCA


In [ ]:
x=10
X=20
print(x)

10


In [ ]:
f1='ATGCGAGT'
f2='TGGTCCA'
f3='are good'
print(f1+f2) #STRING CONCATENATION
print("*************")
print(f1*3)

ATGCGAGTTGGTCCA
*************
ATGCGAGTATGCGAGTATGCGAGT


In [ ]:
len("ATGC")

4

In [ ]:
my_dna = "ATGCGAGT" 
dna_length = len(my_dna) 
print("The length of the DNA sequence is " + str(dna_length))
print("The length of the DNA sequence is " , dna_length)

The length of the DNA sequence is 8
The length of the DNA sequence is  8


In [ ]:
my_dna = "atgc"
low1=my_dna.upper()
print(low1)
low2=low1.lower()
print(low2)


ATGC
atgc


In [ ]:
String1 = "PGDCB STUDENTS"
print("Initial String: ")  
print(String1)  
    
# Printing First character  
print("\nFirst character of String is: ")  
print(String1[0])  
    
# Printing Last character  
print("\nLast character of String is: ")  
print(String1[-1])  

print("\n8th char: ")  
print(String1[8]) 
#  Updation or deletion of characters from a String is not allowed
# because strings are immutable

string2 = 'I\'m doing "Python Progmg"'
print("\n Escaping Single Quote:" , string2)

string2 = " PGDCB \"Python Progmg\" "
print("\n Escaping Double Quote:" , string2)

Initial String: 
PGDCB STUDENTS

First character of String is: 
P

Last character of String is: 
S

8th char: 
U

 Escaping Single Quote: I'm doing "Python Progmg"

 Escaping Double Quote:  PGDCB "Python Progmg" 


In [ ]:
#[start:end]   or [start:end:step]
import numpy as np
arr = np.array([11,12,13,14,15,16,17])
print(arr[-3:-1])
print(arr[1:5])
print(arr[4:]) 
print(arr[:4])
print(arr[-5:-1])
print(arr[1:5:2])
print(arr[::2])

[15 16]
[12 13 14 15]
[15 16 17]
[11 12 13 14]
[13 14 15 16]
[12 14]
[11 13 15 17]


In [ ]:
a=(89+98+54+78+99)/5
print(a)

83.6


In [ ]:
# Python Program to convert temperature in celsius to fahrenheit

# change this value for a different result
celsius = 37.5

# calculate fahrenheit
fahrenheit = (celsius * 1.8) + 32
print(celsius,"degree Celsius is equal to",fahrenheit,"degree Fahrenheit")

37.5 degree Celsius is equal to 99.5 degree Fahrenheit


In [ ]:
r = int(input("Enter the radius of the circle: "))
area = 3.14 * r * r
print("Area of Circle=",area)

Enter the radius of the circle: 3
Area of Circle= 28.259999999999998


In [ ]:
# Python Program to find the area of triangle

a = 5
b = 6
c = 7

# Uncomment below to take inputs from the user
# a = float(input('Enter first side: '))
# b = float(input('Enter second side: '))
# c = float(input('Enter third side: '))

# calculate the semi-perimeter
s = (a + b + c) / 2

# calculate the area
area = (s*(s-a)*(s-b)*(s-c)) ** 0.5
print('The area of the triangle is =', area)

The area of the triangle is = 14.696938456699069


In [ ]:
p=int(input("Enter the Principal:"))
n=int(input("Enter the no. of years:"))
r=int(input("Enter the rate of interest:"))
print('The principal is=', p) 
print('The no. of years is=', n) 
print('The rate of interest is=',r) 
si = (p * n * r)/100
print('The Simple Interest is=', si) 



Enter the Principal:100000
Enter the no. of years:3
Enter the rate of interest:4
The principal is= 100000
The no. of years is= 3
The rate of interest is= 4
The Simple Interest is= 12000.0


In [ ]:
txt = "PGDCB" [::-1]
print(txt)

BCDGP


In [ ]:
txt = "PGDCB" [::2]
print(txt)

PDB


In [ ]:
def fun1(x):
  return x[::-1]

output = fun1("I wonder how this text looks like backwards")

print(output)


sdrawkcab ekil skool txet siht woh rednow I


In [ ]:
#Accessing Elements in Reversed Order
#If you need to access individual elements of a list in the reverse order, it's better to use reversed() function.
# Operating System List
systems = ['Windows', 'macOS', 'Linux']

# Printing Elements in Reversed Order
for o in reversed(systems):
    print(o)

Linux
macOS
Windows


In [ ]:
ranks = ["kingdom","phylum", "class", "order", "family"] 
print(ranks) 
ranks.reverse() 
print(ranks) 
ranks.sort() 
print(ranks)
for i in ranks:
  ranks.reverse()
  #line2
  #line3
print(ranks)

['kingdom', 'phylum', 'class', 'order', 'family']
['family', 'order', 'class', 'phylum', 'kingdom']
['class', 'family', 'kingdom', 'order', 'phylum']
['phylum', 'order', 'kingdom', 'family', 'class']


In [ ]:
mylist = ["kingdom","phylum", "class", "order", "family"] 
#mylist.reverse()
newList = [x[::-1] for x in mylist]
print(newList)

['modgnik', 'mulyhp', 'ssalc', 'redro', 'ylimaf']


In [ ]:
#String that holds the amino-acid sequence of a signal peptide
signal_peptide="MASKATLLLAFTLLFATCIA"
print(signal_peptide)
sp1=signal_peptide.lower()
print(sp1)
sp2=sp1.upper()
print(sp2)

MASKATLLLAFTLLFATCIA
maskatlllaftllfatcia
MASKATLLLAFTLLFATCIA


In [ ]:
#Methods Associated with Strings
#replace(old,new[,count]): Allows us to replace a portion of a string (old) with another (new)
DNAseq="TTGCTAG"
mRNAseq=DNAseq.replace("T","U")
print(mRNAseq)
# If the optional argument count is used, only the first count occurrences of old will be replaced
mRNAseq1=DNAseq.replace("T","U",2)
print(mRNAseq1)

UUGCUAG
UUGCTAG


In [ ]:
#count(sub[, start[, end]]): Counts how many times the substring sub appears, between start and end position
'''
Signal peptide is a short amino acid chain (about 20 amino acids) that is recognized
by certain organelles to direct the transport of the nascent protein to a specific subcellular
location or to the secretory pathway.

CG content is the amount of cytosine and guanine in a DNA sequence. CG content is
related to the DNA melting temperature and other physical properties.
'''

DNAseq="TTGCTACG"
c=DNAseq.count("C")
print(c)
g=DNAseq.count("G")
print(g)
x=float(c+g)/len(DNAseq)*100
print(x)

2
2
50.0


In [ ]:
'''
find(sub[,start[,end]]): Returns the position of the substring sub, between
start and end position (if available). If the substring is not found in
the string, this method returns the value -1.
'''
mRNAseq2="TTGCTACG"
print (mRNAseq2)
print(mRNAseq2.find("TA"))
print(mRNAseq2.find("AUG"))

TTGCTACG
4
-1


In [ ]:
'''
split([sep [,maxsplit]]): Separates the “words” of a string and returns
them in a list. If a separator (sep) is not specified, the default separator will
be the white space.
'''
str ="This string has words separated by spaces".split()
print(str)
s = "this is my string"
s.split(maxsplit=1)
['this', 'is my string']

['This', 'string', 'has', 'words', 'separated', 'by', 'spaces']


['this', 'is my string']

In [ ]:
'''
The inverse function of split() is join().
join(seq) Joins the sequence using a string as a “glue character”
'''
' '.join(['A','C','A','T'])

'A C A T'

In [ ]:
numList = ['1', '2', '3', '4']
separator = ', '
print(separator.join(numList))

# .join() with tuples
numTuple = ('1', '2', '3', '4')
print(separator.join(numTuple))

s1 = 'abc'
s2 = '123'

# each element of s2 is separated by s1
# '1'+ 'abc'+ '2'+ 'abc'+ '3'
print('s1.join(s2):', s1.join(s2))

# each element of s1 is separated by s2
# 'a'+ '123'+ 'b'+ '123'+ 'b'
print('s2.join(s1):', s2.join(s1))

1, 2, 3, 4
1, 2, 3, 4
s1.join(s2): 1abc2abc3
s2.join(s1): a123b123c


In [ ]:
# Creating a Set with a mixed type of values (Having numbers and strings)  
set1 = set([1,3, 2, 'pgdcb', 4, 'Good', 6, 'students'])  
print("\nSet with the use of Mixed Values")  
print(set1) 


Set with the use of Mixed Values
{1, 2, 3, 4, 'pgdcb', 6, 'students', 'Good'}


In [ ]:
# Creating a Set with a mixed type of values (Having numbers and strings)  
set1 = set([1, 2, 'pgdcb', 4, 'Good', 6, 'students'])  
print("\nSet with the use of Mixed Values")  
print(set1) 


Set with the use of Mixed Values
{1, 2, 4, 'pgdcb', 6, 'students', 'Good'}


In [ ]:
print(type(True))  
print(type(False))  
print(type(true))  


<class 'bool'>
<class 'bool'>


NameError: ignored

In [ ]:
#Python program to demonstrate Creation of List   
    
# Creating a List  
List = []  
print("Intial blank List: ")  
print(List)  
    
# Creating a List with  the use of a String  
List = ['VAL1003 STUDENTS']  
print("\nList with the use of String: ")  
print(List)  
    
# Creating a List with the use of multiple values  
List = ["VAL1003", "PYTHON", "STUDENTS"]  
print("\nList containing multiple values: ")  
print(List[0])   
print(List[2])  
    
# Creating a Multi-Dimensional List (By Nesting a list inside a List)  
List1 = [['VAL1003', 'PYTHON'], ['STUDENTS']]  
print("\nMulti-Dimensional List: ")  
print(List1[0]) 


In [ ]:
data={103:'Ravi' ,101:'Vijay' ,102:'Rahul'} 
print( data )

{103: 'Ravi', 101: 'Vijay', 102: 'Rahul'}


In [ ]:
li=[10,2,"Asha",10.5,3,45]
print(li)

[10, 2, 'Asha', 10.5, 3, 45]


In [ ]:
tu=(10,2,3,45)
print(tu)

(10, 2, 3, 45)


In [ ]:
# Creating a Set with a mixed type of values (Having numbers and strings)  
set1 = set([1, 2, 'pgdcb', 4, 'Good', 6, 'students'])  
print("\nSet with the use of Mixed Values")  
print(set1) 


Set with the use of Mixed Values
{1, 'pgdcb', 2, 4, 6, 'Good', 'students'}


In [ ]:
data={103:'Ravi' ,101:'Vijay' ,102:'Rahul'} 
print( data )

{103: 'Ravi', 101: 'Vijay', 102: 'Rahul'}


In [ ]:
data={'A': "hi",103:'Ravi' ,101:'Vijay' ,102:'Rahul'} 
print( data )

{'A': 'hi', 103: 'Ravi', 101: 'Vijay', 102: 'Rahul'}


In [ ]:
apes = ["Homo sapiens", "Pan troglodytes", "Gorilla gorilla"] 
monkeys = ["Papio ursinus", "Macaca mulatta"] 
primates = apes + monkeys 
print(primates)

['Homo sapiens', 'Pan troglodytes', 'Gorilla gorilla', 'Papio ursinus', 'Macaca mulatta']


In [ ]:
def unique_list(l):
  x = []
  for a in l:
    if a not in x:
      x.append(a)
  return x

print(unique_list([1,2,3,3,3,3,4,5])) 

[1, 2, 3, 4, 5]


In [ ]:
#Python program to demonstrate Creation of List   
    
# Creating a List  
List = []  
print("Intial blank List: ")  
print(List)  
    
# Creating a List with  the use of a String  
List = ['IIIBSCSTUDENTS']  
print("\nList with the use of String: ")  
print(List)  
    
# Creating a List with the use of multiple values  
List = ["III", "BSC", "STUDENTS"]  
print("\nList containing multiple values: ")  
print(List[0])   
print(List[2])  
    
# Creating a Multi-Dimensional List (By Nesting a list inside a List)  
List = [['III', 'BSC'], ['STUDENTS']]  
print("\nMulti-Dimensional List: ")  
print(List[0]) 
print(List[1])
# Creating a Multi-Dimensional List (By Nesting a list inside a List)  
List = [['III', 'BSC'], ['STUDENTS']]  
print("\nMulti-Dimensional List: ")  
print(List[0]) 
print(List[-2])
print("Original List=", List)
#Append an element (ADD an element)
List.append(8)  
print("\nList after Adding a number: ")  
print(List) 
print("Original List=", List)
# Addition of Element at specific Position (using Insert Method)  
List.insert(2, 12) 
print(List)  
List.insert(0, 'Geeks')  
print("\nList after performing Insert Operation: ")  
print(List)  
# Addition of multiple elements to the List at the end (using Extend Method)  
List.extend([16, 'Geeks', 'Always'])  
print("\nList after performing Extend Operation: ")  
print(List)  
List1=[11,12,13,14,15,16,17,18]
# accessing a element from the list using index number  
print("Accessing element from the list")  
print(List1[0])   
print(List1[2])  
# accessing a element using negative indexing  
print("Accessing element using negative indexing")  
# print the last element of list  
print(List1[-1])  
# print the third last element of list   
print(List1[-3])
List1=[11,12,13,14,15,16,17,18]
print(List1)
List1.pop()  
print("\nList after popping an element: ")  
print(List1)      
# Removing element at a specific location from the set using the pop() method  
List1.pop(-2)  
print("\nList after popping a specific element: ")  
print(List1)  


Intial blank List: 
[]

List with the use of String: 
['IIIBSCSTUDENTS']

List containing multiple values: 
III
STUDENTS

Multi-Dimensional List: 
['III', 'BSC']
['STUDENTS']

Multi-Dimensional List: 
['III', 'BSC']
['III', 'BSC']
Original List= [['III', 'BSC'], ['STUDENTS']]

List after Adding a number: 
[['III', 'BSC'], ['STUDENTS'], 8]
Original List= [['III', 'BSC'], ['STUDENTS'], 8]
[['III', 'BSC'], ['STUDENTS'], 12, 8]

List after performing Insert Operation: 
['Geeks', ['III', 'BSC'], ['STUDENTS'], 12, 8]

List after performing Extend Operation: 
['Geeks', ['III', 'BSC'], ['STUDENTS'], 12, 8, 16, 'Geeks', 'Always']
Accessing element from the list
11
13
Accessing element using negative indexing
18
16
[11, 12, 13, 14, 15, 16, 17, 18]

List after popping an element: 
[11, 12, 13, 14, 15, 16, 17]

List after popping a specific element: 
[11, 12, 13, 14, 15, 17]


In [ ]:
List = [['III', 'BSC'], ['STUDENTS']]  
print("Original List=", List)
#Append an element (ADD an element)
List.append(8)  
print("\nList after Adding a number: ")  
print(List) 

Original List= [['III', 'BSC'], ['STUDENTS']]

List after Adding a number: 
[['III', 'BSC'], ['STUDENTS'], 8]


In [ ]:
print("Original List=", List)
# Addition of Element at specific Position (using Insert Method)  
List.insert(1, 12) 

Original List= [['III', 'BSC'], 12, ['STUDENTS'], 8]


In [ ]:
List1=[11,12,13]
print(List1)
List1.insert(4,50)
print(List1)

[11, 12, 13]
[11, 12, 13, 50]


In [ ]:
# Python program to demonstrate creation of Tuple 
    
# Creating an empty tuple  
Tuple1 = ()  
print("Initial empty Tuple: ")  
print (Tuple1)  
    
# Creating a Tuple with the use of Strings  
Tuple1 = ('pgdcb', 'students')  
print("\nTuple with the use of String: ")  
print(Tuple1)  
    
# Creating a Tuple with the use of list  
list1 = [1, 2, 4, 5, 6]  
print("\nTuple using List: ")  
print(tuple(list1))  
  
# Creating a Tuple with the use of built-in function  
Tuple1 = tuple('PGDCB')  
print("\nTuple with the use of function: ")  
print(Tuple1)  
  
# Creating a Tuple with nested tuples  
Tuple1 = (0, 1, 2, 3)  
Tuple2 = ('python', 'pgdcb')  
Tuple3 = (Tuple1, Tuple2)  
print("\nTuple with nested tuples: ")  
print(Tuple3)  

# Accessing element using indexing 
print("Frist element of tuple") 
print(Tuple1[0]) 
  
# Accessing element from last -- negative indexing 
print("\nLast element of tuple") 
print(Tuple1[-1]) 
  
print("\nThird last element of tuple") 
print(Tuple1[-3]) 



Initial empty Tuple: 
()

Tuple with the use of String: 
('pgdcb', 'students')

Tuple using List: 
(1, 2, 4, 5, 6)

Tuple with the use of function: 
('P', 'G', 'D', 'C', 'B')

Tuple with nested tuples: 
((0, 1, 2, 3), ('python', 'pgdcb'))
Frist element of tuple
0

Last element of tuple
3

Third last element of tuple
1


In [ ]:
# Python Program
#Creating an empty Dictionary  
Dict = {}  
print("Empty Dictionary: ")  
print(Dict)  
    
# Creating a Dictionary  with Integer Keys  
Dict = {1: 'pgdcb', 2: 'Good', 3: 'students'}  
print("\nDictionary with the use of Integer Keys: ")  
print(Dict)  
    
# Creating a Dictionary with Mixed keys  
Dict = {'Name': 'pgdcb', 1: [1, 2, 3, 4]}  
print("\nDictionary with the use of Mixed Keys: ")  
print(Dict)  
    
# Creating a Dictionary with dict() method  
Dict = dict({1: 'pgdcb', 2: 'Good', 3:'students'})  
print("\nDictionary with the use of dict(): ")  
print(Dict)  
    
# Creating a Dictionary  with each item as a Pair  
Dict = dict([(1, 'pgdcb'), (2, 'Good')])  
print("\nDictionary with each item as a pair: ")  
print(Dict)  

# Adding elements one at a time  
Dict[0] = 'pgdcb'
Dict[2] = 'Good'
Dict[3] = 1
print("\nDictionary after adding 3 elements: ")  
print(Dict)  
  
# Updating existing Key's Value  
Dict[2] = 'Welcome'
print("\nUpdated key value: ")  
print(Dict)  


#Methods used:
# Python program to demonstrate for accessing elements from a Dictionary   
    
# Creating a Dictionary   
Dict = {1: 'pgdcb', 'name': 'For', 3: 'students'}  
    
# accessing a element using key  
print("Accessing a element using key:")  
print(Dict['name'])  
  
# accessing a element using get() method  
print("Accessing a element using get:")  
print(Dict.get(3)) 
 
# Initial Dictionary  
Dict = { 5 : 'Welcome', 6 : 'To', 7 : 'pgdcb',  
        'A' : {1 : 'pgdcb', 2 : 'good', 3 : 'students'},  
        'B' : {1 : 'pgdcb', 2 : 'BRilliant'}}  
print("Initial Dictionary: ")  
print(Dict)  
    
# Deleting a Key value  
del Dict[6]  
print("\nDeleting a specific key: ")  
print(Dict)  
  
# Deleting a Key using pop()  
Dict.pop(5)  
print("\nPopping specific element: ")  
print(Dict)  
    
# Deleting an arbitrary Key-value pair  using popitem()  
Dict.popitem()  
print("\nPops an arbitrary key-value pair: ")  
print(Dict)  
  
# Deleting entire Dictionary  
Dict.clear()  
print("\nDeleting Entire Dictionary: ")  
print(Dict)  


Empty Dictionary: 
{}

Dictionary with the use of Integer Keys: 
{1: 'pgdcb', 2: 'Good', 3: 'students'}

Dictionary with the use of Mixed Keys: 
{'Name': 'pgdcb', 1: [1, 2, 3, 4]}

Dictionary with the use of dict(): 
{1: 'pgdcb', 2: 'Good', 3: 'students'}

Dictionary with each item as a pair: 
{1: 'pgdcb', 2: 'Good'}

Dictionary after adding 3 elements: 
{1: 'pgdcb', 2: 'Good', 0: 'pgdcb', 3: 1}

Updated key value: 
{1: 'pgdcb', 2: 'Welcome', 0: 'pgdcb', 3: 1}
Accessing a element using key:
For
Accessing a element using get:
students
Initial Dictionary: 
{5: 'Welcome', 6: 'To', 7: 'pgdcb', 'A': {1: 'pgdcb', 2: 'good', 3: 'students'}, 'B': {1: 'pgdcb', 2: 'BRilliant'}}

Deleting a specific key: 
{5: 'Welcome', 7: 'pgdcb', 'A': {1: 'pgdcb', 2: 'good', 3: 'students'}, 'B': {1: 'pgdcb', 2: 'BRilliant'}}

Popping specific element: 
{7: 'pgdcb', 'A': {1: 'pgdcb', 2: 'good', 3: 'students'}, 'B': {1: 'pgdcb', 2: 'BRilliant'}}

Pops an arbitrary key-value pair: 
{7: 'pgdcb', 'A': {1: 'pgdcb', 2

In [ ]:
# Python program to demonstrate Creation of Set in Python  
    
# Creating a Set  
set1 = set()  
print("Intial blank Set: ")  
print(set1)  
    
# Creating a Set with the use of a String  
set1 = set("PGDCB")  
print("\nSet with the use of String: ")  
print(set1)  
  
# Creating a Set with the use of a List  
set1 = set(["pgdcb", "students", "Good"])  
print("\nSet with the use of List: ")  
print(set1)  
  
# Creating a Set with a mixed type of values (Having numbers and strings)  
set1 = set([1, 2, 'pgdcb', 4, 'Good', 6, 'students'])  
print("\nSet with the use of Mixed Values")  
print(set1)  


#Methods used:
set1.add(9)  
print("\nSet after Addition of Three elements: ")  
print(set1)  
  
# Addition of elements to the Set using Update function   
set1.update([10, 11])  
print("\nSet after Addition of elements using Update: ")  
print(set1)  
# Removing elements from Set using Remove() method  
set1.remove(9)  
print("\nSet after Removal of two elements: ")  
print(set1)  
    
# Removing elements from Set  using Discard() method  
set1.discard(4)  

print("\nSet after Discarding two elements: ")  
print(set1)  
  
# Removing element from the Set using the pop() method  
set1.pop()  
print("\nSet after popping an element: ")  
print(set1)  
  
# Removing all the elements from Set using clear() method  
set1.clear()  
print("\nSet after clearing all the elements: ")  
print(set1)  


Intial blank Set: 
set()

Set with the use of String: 
{'C', 'P', 'B', 'G', 'D'}

Set with the use of List: 
{'students', 'Good', 'pgdcb'}

Set with the use of Mixed Values
{1, 2, 4, 6, 'Good', 'students', 'pgdcb'}

Set after Addition of Three elements: 
{1, 2, 4, 6, 9, 'Good', 'students', 'pgdcb'}

Set after Addition of elements using Update: 
{1, 2, 4, 6, 9, 10, 11, 'Good', 'students', 'pgdcb'}

Set after Removal of two elements: 
{1, 2, 4, 6, 10, 11, 'Good', 'students', 'pgdcb'}

Set after Discarding two elements: 
{1, 2, 6, 10, 11, 'Good', 'students', 'pgdcb'}

Set after popping an element: 
{2, 6, 10, 11, 'Good', 'students', 'pgdcb'}

Set after clearing all the elements: 
set()


In [ ]:
# Python program to demonstrate Creation of Set in Python  
    
# Creating a Set  
set1 = set()  
print("Intial blank Set: ")  
print(set1)  
    
# Creating a Set with the use of a String  
set1 = set("PGDCB")  
print("\nSet with the use of String: ")  
print(set1)  
  
# Creating a Set with the use of a List  
set1 = set(["pgdcb", "students", "Good"])  
print("\nSet with the use of List: ")  
print(set1)  
  
# Creating a Set with a mixed type of values (Having numbers and strings)  
set1 = set([1, 2, 'pgdcb', 4, 'Good', 6, 'students'])  
print("\nSet with the use of Mixed Values")  
print(set1)  


#Methods used:
set1.add(9)  
print("\nSet after Addition of Three elements: ")  
print(set1)  
  
# Addition of elements to the Set using Update function   
set1.update([10, 11])  
print("\nSet after Addition of elements using Update: ")  
print(set1)  
# Removing elements from Set using Remove() method  
set1.remove(9)  
print("\nSet after Removal of two elements: ")  
print(set1)  
    
# Removing elements from Set  using Discard() method  
set1.discard(4)  

print("\nSet after Discarding two elements: ")  
print(set1)  
  
# Removing element from the Set using the pop() method  
set1.pop()  
print("\nSet after popping an element: ")  
print(set1)  
  
# Removing all the elements from Set using clear() method  
set1.clear()  
print("\nSet after clearing all the elements: ")  
print(set1)  
